//! The streaming section indexer (TODO 2.2) and timeline-event parser (2.5).
//!
//! One pass over the line stream, finding section boundaries **without parsing
//! bodies** — this is what makes a 1 GB file open instantly (PLAN §3.3). The
//! pass is incremental: `ingest` consumes whatever complete lines have arrived
//! and picks up where it left off on the next chunk.
//!
//! Anchoring rules (spike-findings.md §2):
//!
//! - A compilation is anchored on `Compiling 0x… <JSFunction …> with <Tier>`,
//!   which exists in every corpus version. `Begin compiling method` does not
//!   exist before V8 15.2 and is only a preamble/display-name supplement.
//! - Phase banners share one grammar (`----- <name> -----`) with two
//!   non-phases matched specially: `Bytecode array` and `Inlining … with
//!   bytecode` (§9).
//! - The `-----------…` rule lines that 15.2 prints around the begin/finished
//!   banners are buffered as *pending* until the next classified line decides
//!   whether they belong to the closing compilation or the opening one.
//!
//! Everything that is not inside a compilation lands in a [`RawSection`] —
//! the sections partition the file, no line is ever dropped (PLAN principle
//! 1). Single-line lifecycle events (`[marking …]`, `[bailout …]`, `[OSR …]`)
//! are additionally recorded as [`TimelineEvent`]s wherever they appear; an
//! event line also *closes* an open compilation, because deopts happen at run
//! time — with concurrent recompilation this can split an interleaved dump,
//! which degrades the tail to raw per the demultiplexing strategy (PLAN §4.1).

use std::collections::HashMap;
use std::sync::OnceLock;

use regex::Regex;

use crate::ansi;
use crate::markers::{MarkerTable, VersionVotes};
use crate::model::{
    Addr, CompilationKey, CompilationSection, Confidence, EventKind, OsrInfo, PhaseKind,
    PhaseSection, RawSection, Tier, TimelineEvent,
};
use crate::source::LogBuffer;

/// Compiled once; the indexer runs per line and must stay cheap.
struct Res {
    compiling: Regex,
    begin: Regex,
    finished: Regex,
    banner: Regex,
    rule: Regex,
    inlining_banner: Regex,
    ev_marking: Regex,
    ev_compile_start: Regex,
    ev_compile_done: Regex,
    ev_deopt_begin: Regex,
    ev_deopt_end: Regex,
    ev_osr: Regex,
    function_line: Regex,
    /// `[generated bytecode for function: name (0x… <SharedFunctionInfo …>)]`
    /// — the `--print-bytecode` anchor (Phase 8.3).
    bytecode_anchor: Regex,
    /// `0x… <SharedFunctionInfo name>` anywhere in a line — the identity the
    /// TurboFan scan reads out of FrameState nodes (Phase 8.1).
    sfi_object: Regex,
}

fn res() -> &'static Res {
    static RES: OnceLock<Res> = OnceLock::new();
    RES.get_or_init(|| {
        // `<JSFunction name (sfi = 0x…)>` where the name is empty for the
        // toplevel script function (spike-findings.md §11): the ` ?… ?`
        // dance accepts both `JSFunction read (sfi` and `JSFunction (sfi`.
        const FUNC: &str = r"<JSFunction ?([^<>]*?) ?\(sfi = (0x[0-9a-f]+)\)>";
        let re = |s: &str| Regex::new(s).expect("static regex");
        Res {
            compiling: re(&format!(
                r"^Compiling (0x[0-9a-f]+) {FUNC} with (\S+)\s*$"
            )),
            begin: re(r"^Begin compiling method (.*?) using (\S+)\s*$"),
            finished: re(r"^Finished compiling method (.*?) using (\S+)\s*$"),
            banner: re(r"^----- (.+?) -----\s?$"),
            rule: re(r"^-{20,}\s*$"),
            inlining_banner: re(r"^Inlining (0x[0-9a-f]+) <SharedFunctionInfo ?(.*?)> with bytecode$"),
            ev_marking: re(&format!(
                r"^\[marking (?:0x[0-9a-f]+ )?{FUNC} for optimization to ([A-Z_]+),.*reason: (.*?)\]$"
            )),
            ev_compile_start: re(&format!(
                r"^\[compiling method (?:0x[0-9a-f]+ )?{FUNC} \(target ([A-Z_]+)\)( OSR)?, mode: .*\]$"
            )),
            ev_compile_done: re(&format!(
                r"^\[completed compiling (?:0x[0-9a-f]+ )?{FUNC} \(target ([A-Z_]+)\)( OSR)? - took .*\]$"
            )),
            ev_deopt_begin: re(&format!(
                r"^\[bailout \(kind: ([^,]+), reason: (.*?)\): begin\. deoptimizing (?:0x[0-9a-f]+ )?{FUNC}, 0x[0-9a-f]+ <Code ([A-Z_]+)>, opt id (\d+), bytecode offset (\d+),.*\]$"
            )),
            ev_deopt_end: re(r"^\[bailout end\. code_invalidation: (\w+).*\]$"),
            ev_osr: re(r"^\[OSR - ([^.]*)\. function: ([^,\]]*)(?:, osr offset: (\d+))?.*\]$"),
            function_line: re(&format!(r"^Function: (0x[0-9a-f]+) {FUNC}\s*$")),
            bytecode_anchor: re(
                r"^\[generated bytecode for function: (.*?) ?\((0x[0-9a-f]+) <SharedFunctionInfo ?[^>]*>\)\]$",
            ),
            sfi_object: re(r"(0x[0-9a-f]+) <SharedFunctionInfo ?([^>]*)>"),
        }
    })
}

/// TurboFan/Turboshaft banner names are stable across the corpus versions
/// (unlike Maglev's, which all changed between 14.9 and 15.2), so they are
/// recognised by shape rather than enumerated per version — a new pipeline
/// phase is "known" on day one, and contributes no version vote.
fn tf_banner_shape(name: &str) -> bool {
    name.starts_with("Graph after V8.TF")
        || name.starts_with("V8.TFTurboshaft")
        || name == "schedule"
        || name.starts_with("Instruction sequence ")
}

fn contains_subslice(haystack: &[u8], needle: &[u8]) -> bool {
    haystack.windows(needle.len()).any(|w| w == needle)
}

/// `--print-opt-code` section headers, valid only inside a code section.
fn code_subheader(text: &str) -> Option<&'static str> {
    if text.starts_with("Instructions (size") {
        Some("Instructions")
    } else if text.starts_with("Inlined functions (count") {
        Some("Inlined functions")
    } else if text.starts_with("Deoptimization Input Data (") {
        Some("Deoptimization Input Data")
    } else if text.starts_with("Safepoints (") {
        Some("Safepoints")
    } else if text.starts_with("RelocInfo (") {
        Some("RelocInfo")
    } else {
        None
    }
}

/// `--print-bytecode` table headers, valid only inside an Ignition section —
/// the same lines also appear inside Turbolev bytecode dumps, where they are
/// plain phase content.
fn pool_subheader(text: &str) -> Option<&'static str> {
    if text.starts_with("Constant pool (size") {
        Some("Constant pool")
    } else if text.starts_with("Handler Table (size") {
        Some("Handler Table")
    } else if text.starts_with("Source Position Table (size") {
        Some("Source Position Table")
    } else {
        None
    }
}

/// Rule/`Begin compiling` lines seen but not yet attributed: whether they open
/// the next compilation or close the current one depends on the line after
/// them.
#[derive(Debug)]
struct Pending {
    start: usize,
}

#[derive(Debug, Clone, Copy)]
enum State {
    /// Top level. `raw_since` is the start of an open raw section, if any.
    Idle { raw_since: Option<usize> },
    /// Inside compilation `self.compilations[comp]`.
    InCompilation { comp: usize },
}

/// The index of one source: sections that partition the lines, plus the
/// timeline events found along the way.
pub struct TraceIndex {
    pub compilations: Vec<CompilationSection>,
    pub raw: Vec<RawSection>,
    pub events: Vec<TimelineEvent>,
    /// Best guess at the V8 version, from marker-table votes.
    pub detected_version: Option<String>,

    state: State,
    pending: Option<Pending>,
    raw_label: Option<String>,
    next_line: usize,
    ordinals: HashMap<(Addr, Tier), u32>,
    votes: VersionVotes,
    /// Last `[compiling method …]` event: `(sfi, tier, osr)`. Binds the OSR
    /// flag to the next matching graph dump (correlation-keys.md §3 rule 1).
    last_compile_start: Option<(Addr, Tier, bool)>,
    /// Last `[OSR - compilation started]` offset per function *name* — a weak
    /// key, so anything derived from it is marked [`Confidence::Heuristic`].
    osr_offset_by_name: HashMap<String, u32>,
    /// A compilation opened with deferred identity: Turbolev (patched by the
    /// `Function:` line), TurboFan (patched by the first SFI object matching
    /// the Begin-line name), or an opt-code section (patched by its
    /// `name =` / `kind = ` header lines).
    awaiting_identity: Option<usize>,
    /// The open `--print-opt-code` section, when one is (Phase 8.2). Its
    /// sub-headers (`Instructions (size …)` etc.) open phases only there.
    code_section: Option<usize>,
    /// One-shot latches for the open code section's `kind = ` / `name = `
    /// identity lines: a second `--- Optimized code ---` block in the same
    /// section must not bump the ordinal again or rename it.
    code_kind_seen: bool,
    code_name_seen: bool,
    /// Lines left before the TurboFan identity scan gives up. Bounded so an
    /// unidentifiable section costs O(budget), not O(section) (found in
    /// review: ~380 ns/line over millions of lines).
    identity_budget: usize,
    function_filter: Option<Regex>,
}

impl TraceIndex {
    pub fn new(function_filter: Option<Regex>) -> Self {
        Self {
            compilations: Vec::new(),
            raw: Vec::new(),
            events: Vec::new(),
            detected_version: None,
            state: State::Idle { raw_since: None },
            pending: None,
            raw_label: None,
            next_line: 0,
            ordinals: HashMap::new(),
            votes: VersionVotes::default(),
            last_compile_start: None,
            osr_offset_by_name: HashMap::new(),
            awaiting_identity: None,
            code_section: None,
            code_kind_seen: false,
            code_name_seen: false,
            identity_budget: 0,
            function_filter,
        }
    }

    /// Consumes complete lines that arrived since the last call. While the
    /// source is still streaming, the final line may be a partial one whose
    /// bytes are not all here yet, so it is held back until `finished`.
    pub fn ingest(&mut self, buffer: &LogBuffer, finished: bool) {
        let started = std::time::Instant::now();
        let from = self.next_line;
        let mut end = buffer.line_count();
        if !finished {
            end = end.saturating_sub(1);
        }
        while self.next_line < end {
            let i = self.next_line;
            let line = buffer.line(i).unwrap_or(b"");
            self.step(i, line);
            self.next_line += 1;
        }
        if finished {
            self.close_all(buffer.line_count());
            self.detected_version = self.votes.detected().map(str::to_string);
        }
        // Alongside the line-index timing in LogBuffer, this is the other
        // O(file) step on the open path (PLAN §12: 500 MB < 2 s).
        if self.next_line - from > 100_000 {
            tracing::debug!(
                lines = self.next_line - from,
                compilations = self.compilations.len(),
                events = self.events.len(),
                micros = started.elapsed().as_micros(),
                "sections indexed"
            );
        }
    }

    /// The number of lines fully indexed so far.
    pub fn lines_indexed(&self) -> usize {
        self.next_line
    }

    fn step(&mut self, i: usize, line: &[u8]) {
        // Fast path: only a handful of first bytes can start a boundary line
        // (`-----`, `Begin`, `Compiling`, `Finished`, `[event]`, and the
        // Phase 8 listing headers `Instructions`/`Deoptimization`/
        // `Safepoints`/`RelocInfo`/`Handler`/`Source`), possibly behind an
        // ANSI escape. Everything else — the vast majority of graph body
        // lines — extends the current section with no further work.
        match line.first() {
            Some(b'-' | b'B' | b'C' | b'F' | b'[' | b'I' | b'D' | b'S' | b'R' | b'H' | 0x1b) => {
                let stripped = ansi::strip(line);
                match std::str::from_utf8(&stripped) {
                    Ok(text) => self.classify(i, text),
                    Err(_) => self.content(i, line),
                }
            }
            _ => self.content(i, line),
        }
    }

    fn classify(&mut self, i: usize, text: &str) {
        let r = res();

        // Cheap prefix guards before any regex runs.
        if text.starts_with("-----") {
            if let Some(c) = r.banner.captures(text) {
                self.on_banner(i, &c[1]);
                return;
            }
            if r.rule.is_match(text) {
                self.on_rule(i);
                return;
            }
        } else if text.starts_with("--- ") {
            // `--print-opt-code` section markers (Phase 8.2). `--- BLOCK B0
            // id0 ---` (the TurboFan schedule) shares the prefix and falls
            // through to content.
            match text.trim_end() {
                "--- Raw source ---" => {
                    self.on_code_source(i);
                    return;
                }
                "--- Optimized code ---" => {
                    self.on_code_header(i);
                    return;
                }
                "--- End code ---" if self.on_code_end(i) => {
                    return;
                }
                _ => {}
            }
        } else if text.starts_with("Compiling ") {
            if let Some(c) = r.compiling.captures(text) {
                let (addr, name, sfi, tier) = (&c[1], &c[2], &c[3], &c[4]);
                self.on_compiling(i, addr, name, sfi, tier);
                return;
            }
        } else if text.starts_with("Begin compiling method ") {
            if let Some(c) = r.begin.captures(text) {
                let (name, tier) = (c[1].to_string(), c[2].to_string());
                self.on_begin(i, &name, &tier);
                return;
            }
        } else if text.starts_with("Finished compiling method ") {
            if let Some(c) = r.finished.captures(text) {
                let (name, tier) = (c[1].to_string(), c[2].to_string());
                self.on_finished(i, text, &name, &tier);
                return;
            }
        } else if text.starts_with("Function: ") {
            if let Some(c) = r.function_line.captures(text) {
                let (addr, name, sfi) = (c[1].to_string(), c[2].to_string(), c[3].to_string());
                self.on_function_identity(i, &addr, &name, &sfi);
                return;
            }
        } else if text.starts_with("[generated bytecode for function:") {
            // Must run before the generic event parse: it is also a `[…]`
            // line (Phase 8.3).
            if let Some(c) = r.bytecode_anchor.captures(text) {
                let (name, sfi) = (c[1].to_string(), c[2].to_string());
                self.on_bytecode_anchor(i, &name, &sfi);
                return;
            }
        } else if text.starts_with('[') {
            if let Some(kind) = parse_event(text) {
                self.on_event(i, kind, text);
                return;
            }
        } else if let Some(name) = code_subheader(text) {
            if self.on_code_phase(i, name) {
                return;
            }
        } else if let Some(name) = pool_subheader(text) {
            if self.on_pool_phase(i, name) {
                return;
            }
        }

        self.content(i, text.as_bytes());
    }

    /// A non-boundary line: extends whatever is open. Compilation extents are
    /// kept live so that a still-streaming compilation is viewable (and its
    /// parse cache invalidates) before it closes.
    fn content(&mut self, i: usize, line: &[u8]) {
        self.flush_pending_into_current();
        self.scan_identity(line);
        match &mut self.state {
            State::InCompilation { comp } => {
                let section = &mut self.compilations[*comp];
                section.lines.end = i + 1;
                if let Some(open) = section.phases.last_mut() {
                    open.lines.end = i + 1;
                } else {
                    section.preamble.end = i + 1;
                }
            }
            State::Idle { raw_since } => {
                if raw_since.is_none() {
                    *raw_since = Some(i);
                    self.raw_label = None;
                }
                if self.raw_label.is_none() && !line.is_empty() {
                    self.raw_label = Some(label_from(line));
                }
            }
        }
    }

    fn on_rule(&mut self, i: usize) {
        // Ambiguous until the next line: 15.2 prints a rule both before
        // `Finished compiling` (belongs to the closing compilation) and before
        // `Begin compiling` (belongs to the opening one).
        if self.pending.is_none() {
            self.pending = Some(Pending { start: i });
        }
    }

    fn on_begin(&mut self, i: usize, name: &str, tier: &str) {
        let tier = Tier::parse(tier);
        if tier == Tier::Maglev {
            // 15.2 Maglev: a `Compiling 0x…` anchor follows; the Begin line
            // stays pending until it decides ownership.
            if self.pending.is_none() {
                self.pending = Some(Pending { start: i });
            }
            return;
        }
        // TurboFan (`--trace-turbo-graph`) has no `Compiling` line at all —
        // the Begin line *is* the anchor (Phase 8.1). Identity (the SFI) is
        // patched later from the first SFI object in the body that matches
        // this name; the ordinal is assigned then too.
        let cut = self.pending.take().map(|p| p.start).unwrap_or(i);
        self.close_all(cut);
        let filtered_out = self.filtered_out_by_name(name);
        let ordinal = self.provisional_ordinal(&tier);
        self.compilations.push(CompilationSection {
            key: CompilationKey {
                sfi: Addr(0),
                tier,
                ordinal,
            },
            name: name.to_string(),
            function_addr: None,
            lines: cut..i + 1,
            osr: None,
            phases: Vec::new(),
            preamble: i + 1..i + 1,
            filtered_out,
        });
        let comp = self.compilations.len() - 1;
        self.state = State::InCompilation { comp };
        self.awaiting_identity = Some(comp);
        self.identity_budget = 5_000;
    }

    /// A provisional 1-based ordinal for a section whose identity has not
    /// arrived (keyed on the placeholder `Addr(0)`); re-keyed if identity
    /// does arrive. Guarantees the documented "1-based instance count"
    /// invariant even when identity never shows up (found in review:
    /// unidentified sections rendered as `#0` with duplicate keys).
    fn provisional_ordinal(&mut self, tier: &Tier) -> u32 {
        let n = self.ordinals.entry((Addr(0), tier.clone())).or_insert(0);
        *n += 1;
        *n
    }

    fn filtered_out_by_name(&self, name: &str) -> bool {
        match &self.function_filter {
            Some(re) => {
                let display = if name.is_empty() { "<toplevel>" } else { name };
                !re.is_match(display)
            }
            None => false,
        }
    }

    /// `--- Raw source ---`: opens a `--print-opt-code` section (Phase 8.2).
    /// The source text is the preamble; `--- Optimized code ---` and the
    /// listing headers open phases; `--- End code ---` closes. Identity comes
    /// from the `name = ` / `kind = ` header lines.
    fn on_code_source(&mut self, i: usize) {
        let cut = self.pending.take().map(|p| p.start).unwrap_or(i);
        self.close_all(cut);
        self.open_code_section(cut, i);
    }

    fn open_code_section(&mut self, cut: usize, i: usize) {
        let ordinal = self.provisional_ordinal(&Tier::Turbofan);
        self.compilations.push(CompilationSection {
            key: CompilationKey {
                sfi: Addr(0),
                tier: Tier::Turbofan,
                ordinal,
            },
            name: String::new(),
            function_addr: None,
            lines: cut..i + 1,
            osr: None,
            phases: Vec::new(),
            preamble: i + 1..i + 1,
            filtered_out: false,
        });
        let comp = self.compilations.len() - 1;
        self.state = State::InCompilation { comp };
        self.code_section = Some(comp);
        self.code_kind_seen = false;
        self.code_name_seen = false;
    }

    /// `--- Optimized code ---`: a phase of the open code section — or the
    /// anchor itself. The `Raw source` block is *optional* in V8's output
    /// (only printed when script source is available), so this line must be
    /// able to open the section too (found in review: a dump without source
    /// degraded entirely to raw).
    fn on_code_header(&mut self, i: usize) {
        if self.on_code_phase(i, "Optimized code") {
            return;
        }
        let cut = self.pending.take().map(|p| p.start).unwrap_or(i);
        self.close_all(cut);
        self.open_code_section(cut, i);
        let comp = self.compilations.len() - 1;
        // The anchor line heads its own phase; there is no preamble.
        self.compilations[comp].preamble = i..i;
        self.compilations[comp].phases.push(PhaseSection {
            name: "Optimized code".to_string(),
            kind: PhaseKind::Listing,
            lines: i..i + 1,
        });
    }

    /// A listing header inside the open code section opens a phase there;
    /// anywhere else the caller keeps it as content.
    fn on_code_phase(&mut self, i: usize, name: &str) -> bool {
        let State::InCompilation { comp } = self.state else {
            return false;
        };
        if self.code_section != Some(comp) {
            return false;
        }
        self.pending = None;
        self.open_phase(comp, i, name.to_string(), PhaseKind::Listing);
        true
    }

    fn on_code_end(&mut self, i: usize) -> bool {
        let State::InCompilation { comp } = self.state else {
            return false;
        };
        if self.code_section != Some(comp) {
            return false;
        }
        self.pending = None;
        self.close_compilation(comp, i + 1);
        self.state = State::Idle { raw_since: None };
        self.code_section = None;
        self.awaiting_identity = None;
        true
    }

    /// `--print-bytecode` table headers open Listing phases only inside an
    /// Ignition section; inside a Turbolev bytecode dump they are content.
    fn on_pool_phase(&mut self, i: usize, name: &str) -> bool {
        let State::InCompilation { comp } = self.state else {
            return false;
        };
        if self.compilations[comp].key.tier != Tier::Ignition {
            return false;
        }
        self.pending = None;
        self.open_phase(comp, i, name.to_string(), PhaseKind::Listing);
        true
    }

    /// `[generated bytecode for function: name (0x… <SharedFunctionInfo …>)]`
    /// — the `--print-bytecode` anchor (Phase 8.3), with full identity on the
    /// anchor line itself.
    fn on_bytecode_anchor(&mut self, i: usize, name: &str, sfi: &str) {
        let cut = self.pending.take().map(|p| p.start).unwrap_or(i);
        self.close_all(cut);
        let sfi = Addr::parse(sfi).unwrap_or(Addr(0));
        let ordinal = {
            let n = self.ordinals.entry((sfi, Tier::Ignition)).or_insert(0);
            *n += 1;
            *n
        };
        let filtered_out = self.filtered_out_by_name(name);
        self.compilations.push(CompilationSection {
            key: CompilationKey {
                sfi,
                tier: Tier::Ignition,
                ordinal,
            },
            name: name.to_string(),
            function_addr: None,
            lines: cut..i + 1,
            osr: None,
            // The anchor line itself heads the bytecode listing, exactly like
            // the Turbolev anchor heads its phase.
            phases: vec![PhaseSection {
                name: "Bytecode array".to_string(),
                kind: PhaseKind::Bytecode,
                lines: i..i + 1,
            }],
            preamble: i..i,
            filtered_out,
        });
        self.state = State::InCompilation {
            comp: self.compilations.len() - 1,
        };
    }

    fn on_compiling(&mut self, i: usize, addr: &str, name: &str, sfi: &str, tier: &str) {
        let cut = self.pending.take().map(|p| p.start).unwrap_or(i);
        self.close_all(cut);

        let sfi = match Addr::parse(sfi) {
            Some(a) => a,
            None => {
                // Cannot happen with the regex above, but never panic on input.
                tracing::error!(line = i, "unparseable sfi address");
                Addr(0)
            }
        };
        let tier = Tier::parse(tier);
        let ordinal = {
            let n = self.ordinals.entry((sfi, tier.clone())).or_insert(0);
            *n += 1;
            *n
        };

        let osr = match &self.last_compile_start {
            Some((event_sfi, event_tier, true)) if *event_sfi == sfi && *event_tier == tier => {
                Some(OsrInfo {
                    offset: self.osr_offset_by_name.get(name).copied(),
                    confidence: if self.osr_offset_by_name.contains_key(name) {
                        Confidence::Heuristic
                    } else {
                        Confidence::Exact
                    },
                })
            }
            _ => None,
        };

        let filtered_out = match &self.function_filter {
            Some(re) => {
                let display = if name.is_empty() { "<toplevel>" } else { name };
                !re.is_match(display)
            }
            None => false,
        };

        self.compilations.push(CompilationSection {
            key: CompilationKey { sfi, tier, ordinal },
            name: name.to_string(),
            function_addr: Addr::parse(addr),
            lines: cut..i + 1,
            osr,
            phases: Vec::new(),
            preamble: i + 1..i + 1,
            filtered_out,
        });
        self.state = State::InCompilation {
            comp: self.compilations.len() - 1,
        };
    }

    /// Opens a Turbolev compilation at its anchor banner. Identity (name,
    /// SFI) arrives later on the `Function:` line inside the section, so the
    /// key is patched in [`Self::on_function_identity`]; ordinals are
    /// assigned there too, once the SFI is known.
    fn on_turbolev_anchor(&mut self, i: usize, banner: &str) {
        // Newer builds print `Begin compiling method X using TurboFan` ahead
        // of a *Turbolev* pipeline dump too — the tier word on that line is
        // misleading. Only this banner reveals which pipeline follows. If
        // the Begin line just opened a TurboFan section that has no phases
        // yet, it was Turbolev all along: convert it in place instead of
        // splitting off a bogus three-line Turbofan section (user report).
        if let State::InCompilation { comp } = self.state
            && self.awaiting_identity == Some(comp)
            && self.code_section != Some(comp)
            && self.compilations[comp].key.tier == Tier::Turbofan
            && self.compilations[comp].phases.is_empty()
        {
            let ordinal = self.provisional_ordinal(&Tier::Turbolev);
            let section = &mut self.compilations[comp];
            section.key.tier = Tier::Turbolev;
            section.key.ordinal = ordinal;
            self.pending = None;
            self.open_phase(comp, i, banner.to_string(), PhaseKind::Bytecode);
            return;
        }

        let cut = self.pending.take().map(|p| p.start).unwrap_or(i);
        self.close_all(cut);

        let ordinal = self.provisional_ordinal(&Tier::Turbolev);
        self.compilations.push(CompilationSection {
            key: CompilationKey {
                sfi: Addr(0),
                tier: Tier::Turbolev,
                ordinal,
            },
            name: String::new(),
            function_addr: None,
            lines: cut..i + 1,
            osr: None,
            phases: vec![PhaseSection {
                name: banner.to_string(),
                kind: PhaseKind::Bytecode,
                lines: i..i + 1,
            }],
            preamble: i..i,
            filtered_out: false,
        });
        let comp = self.compilations.len() - 1;
        self.state = State::InCompilation { comp };
        self.awaiting_identity = Some(comp);
    }

    /// `Function: 0x… <JSFunction name (sfi = 0x…)>` — the identity of a
    /// Turbolev compilation, printed inside its bytecode section.
    fn on_function_identity(&mut self, i: usize, addr: &str, name: &str, sfi: &str) {
        let awaiting = match (self.awaiting_identity, self.state) {
            (Some(comp), State::InCompilation { comp: open }) if comp == open => Some(comp),
            _ => None,
        };
        if let Some(comp) = awaiting {
            let sfi = Addr::parse(sfi).unwrap_or(Addr(0));
            let tier = self.compilations[comp].key.tier.clone();
            let ordinal = {
                let n = self.ordinals.entry((sfi, tier)).or_insert(0);
                *n += 1;
                *n
            };
            let filtered_out = match &self.function_filter {
                Some(re) => {
                    let display = if name.is_empty() { "<toplevel>" } else { name };
                    !re.is_match(display)
                }
                None => false,
            };
            let section = &mut self.compilations[comp];
            section.key.sfi = sfi;
            section.key.ordinal = ordinal;
            section.name = name.to_string();
            section.function_addr = Addr::parse(addr);
            section.filtered_out = filtered_out;
            self.awaiting_identity = None;
        }
        // Either way the line is ordinary content of whatever is open.
        self.content(i, name.as_bytes());
    }

    fn on_finished(&mut self, i: usize, text: &str, name: &str, tier: &str) {
        match self.state {
            // A `Finished compiling` trailer only closes the section it
            // *names*, and only at its own tier — `using Maglev` must not
            // tear down an open TurboFan section an interleaved stream put
            // it inside (found in review), and with concurrent
            // recompilation A's trailer lands inside B's body, where
            // closing B would glue A's end marker onto the wrong section
            // and orphan B's own trailer as raw (user report). Turbolev is
            // the tier exception: its pipeline prints TurboFan on the
            // Begin/Finished trailers (the tier word is misleading there).
            State::InCompilation { comp }
                if {
                    let section = &self.compilations[comp];
                    let line_tier = Tier::parse(tier);
                    let tier_ok = section.key.tier == line_tier
                        || (section.key.tier == Tier::Turbolev && line_tier == Tier::Turbofan);
                    tier_ok && section.name == name
                } =>
            {
                // The pending rule (if any) belongs to this compilation, and so
                // does the Finished line itself.
                self.pending = None;
                self.close_compilation(comp, i + 1);
                self.state = State::Idle { raw_since: None };
                self.awaiting_identity = None;
                self.code_section = None;
            }
            _ => {
                // No open compilation, or the wrong tier: raw content.
                self.content(i, text.as_bytes());
            }
        }
    }

    fn on_banner(&mut self, i: usize, name: &str) {
        // The Turbolev frontend has no `Compiling … with <Tier>` line; this
        // banner *is* the compilation anchor (`--print-turbolev-frontend`).
        if name == "Bytecode before MaglevGraphBuilding" {
            self.on_turbolev_anchor(i, name);
            return;
        }
        let State::InCompilation { comp } = self.state else {
            // Banner grammar outside a compilation (TurboFan graphs, Phase 8
            // material): raw fallback, never dropped.
            self.content(i, name.as_bytes());
            return;
        };
        // A pending rule inside a compilation followed by a banner is just
        // body content; forget it.
        self.pending = None;

        let kind = if name == "Bytecode array" {
            PhaseKind::Bytecode
        } else if let Some(c) = res().inlining_banner.captures(name) {
            PhaseKind::Inlining {
                sfi: Addr::parse(&c[1]),
                callee: c[2].to_string(),
            }
        } else {
            let known = match MarkerTable::get().phase_versions(name) {
                Some(versions) => {
                    self.votes.record(versions);
                    true
                }
                // Not in the version table: TurboFan banners are known by
                // shape (they never changed between corpus versions and
                // carry no version signal).
                None => tf_banner_shape(name),
            };
            PhaseKind::Graph { known }
        };

        self.open_phase(comp, i, name.to_string(), kind);
    }

    /// Closes the open phase (or preamble) at `i` and starts a new one there.
    fn open_phase(&mut self, comp: usize, i: usize, name: String, kind: PhaseKind) {
        let section = &mut self.compilations[comp];
        section.lines.end = i + 1;
        if let Some(open) = section.phases.last_mut() {
            open.lines.end = i;
        } else {
            section.preamble.end = i;
        }
        section.phases.push(PhaseSection {
            name,
            kind,
            lines: i..i + 1,
        });
    }

    fn on_event(&mut self, i: usize, kind: EventKind, text: &str) {
        match &kind {
            EventKind::CompileStart {
                sfi: Some(sfi),
                target,
                osr,
                ..
            } => {
                self.last_compile_start = Some((*sfi, target.clone(), *osr));
            }
            EventKind::Osr {
                what,
                name,
                osr_offset: Some(offset),
            } if what.starts_with("compilation started") => {
                self.osr_offset_by_name.insert(name.clone(), *offset);
            }
            _ => {}
        }
        self.events.push(TimelineEvent { line: i, kind });

        // Lifecycle events happen at run time, outside compile dumps; one
        // arriving inside a dump means interleaving, and the tail degrades to
        // raw (module doc). The event line itself is raw content.
        if matches!(self.state, State::InCompilation { .. }) {
            let cut = self.pending.take().map(|p| p.start).unwrap_or(i);
            self.close_all(cut);
            // Pending rule/Begin lines between the cut and the event would
            // otherwise belong to no section, breaking the partition
            // invariant; they open the raw section the event lands in.
            if cut < i {
                self.state = State::Idle {
                    raw_since: Some(cut),
                };
                self.raw_label = None;
            }
        }
        self.content(i, text.as_bytes());
    }

    /// Deferred-identity patching from body content (Phase 8): TurboFan
    /// sections take the SFI of the first SFI object whose name matches the
    /// Begin line's; opt-code sections read their `name = ` / `kind = `
    /// header lines. Runs only while an identity is actually awaited, so the
    /// per-line cost on the indexing fast path is one `Option` check.
    fn scan_identity(&mut self, line: &[u8]) {
        let State::InCompilation { comp: open } = self.state else {
            return;
        };
        // Code-section identity is driven by the section itself (its
        // `name =`/`kind =` lines carry one-shot latches), not by
        // `awaiting_identity`.
        if self.code_section == Some(open) {
            self.scan_code_identity(open, line);
            return;
        }
        let Some(comp) = self.awaiting_identity else {
            return;
        };
        if open != comp {
            return;
        }
        if self.compilations[comp].key.tier == Tier::Turbofan {
            // Bounded: an unidentifiable section must cost O(budget), not
            // O(section) (found in review).
            if self.identity_budget == 0 {
                self.awaiting_identity = None;
                return;
            }
            self.identity_budget -= 1;
            self.scan_tf_identity(comp, line);
        }
        // Turbolev identity arrives on the `Function:` boundary line instead.
    }

    fn scan_tf_identity(&mut self, comp: usize, line: &[u8]) {
        // Only FrameState nodes name the function being compiled; a
        // `HeapConstant[… <JSFunction name (sfi = …)>]` can be a closure of a
        // *different* function that happens to share the name, and node
        // print order guarantees nothing (found in review: the first
        // name-equal object won, wrongly). The name match on top of the
        // FrameState gate keeps inlined-frame SFIs out.
        if !contains_subslice(line, b"FrameState") {
            return;
        }
        let stripped = ansi::strip(line);
        let Ok(text) = std::str::from_utf8(&stripped) else {
            return;
        };
        let r = res();
        let want = self.compilations[comp].name.clone();
        let mut sfi = None;
        for c in r.sfi_object.captures_iter(text) {
            if c[2] == want {
                sfi = Addr::parse(&c[1]);
                break;
            }
        }
        let Some(sfi) = sfi else { return };
        let tier = self.compilations[comp].key.tier.clone();
        let ordinal = {
            let n = self.ordinals.entry((sfi, tier)).or_insert(0);
            *n += 1;
            *n
        };
        let section = &mut self.compilations[comp];
        section.key.sfi = sfi;
        section.key.ordinal = ordinal;
        self.awaiting_identity = None;
    }

    fn scan_code_identity(&mut self, comp: usize, line: &[u8]) {
        if self.code_kind_seen && self.code_name_seen {
            return;
        }
        // Only the `--- Optimized code ---` header block carries the
        // key/value identity lines; source text in the preamble could
        // contain look-alikes.
        if self.compilations[comp]
            .phases
            .last()
            .map(|p| p.name == "Optimized code")
            != Some(true)
        {
            return;
        }
        let stripped;
        let text: &[u8] = if line.contains(&0x1b) {
            stripped = ansi::strip(line);
            &stripped
        } else {
            line
        };
        if let Some(rest) = text.strip_prefix(b"name = ") {
            if !self.code_name_seen
                && let Ok(name) = std::str::from_utf8(rest)
            {
                let name = name.trim().to_string();
                self.compilations[comp].filtered_out = self.filtered_out_by_name(&name);
                self.compilations[comp].name = name;
                self.code_name_seen = true;
            }
        } else if let Some(rest) = text.strip_prefix(b"kind = ") {
            if !self.code_kind_seen
                && let Ok(kind) = std::str::from_utf8(rest)
            {
                let tier = Tier::parse(kind.trim());
                let section = &mut self.compilations[comp];
                if tier != section.key.tier {
                    // Re-key under the printed kind; the provisional ordinal
                    // was assigned under Turbofan.
                    let n = self.ordinals.entry((Addr(0), tier.clone())).or_insert(0);
                    *n += 1;
                    let ordinal = *n;
                    let section = &mut self.compilations[comp];
                    section.key.tier = tier;
                    section.key.ordinal = ordinal;
                }
                self.code_kind_seen = true;
            }
        }
    }

    /// A pending rule/begin that turned out to precede ordinary content
    /// belongs to whatever is open (or opens a raw section).
    fn flush_pending_into_current(&mut self) {
        let Some(p) = self.pending.take() else { return };
        if let State::Idle { raw_since } = &mut self.state {
            if raw_since.is_none() {
                *raw_since = Some(p.start);
                self.raw_label = None;
            }
        }
    }

    fn close_compilation(&mut self, comp: usize, end: usize) {
        let section = &mut self.compilations[comp];
        section.lines.end = end;
        if let Some(open) = section.phases.last_mut() {
            open.lines.end = end;
        } else {
            section.preamble.end = end;
        }
    }

    /// Closes whatever is open so that the sections partition `0..end`.
    fn close_all(&mut self, end: usize) {
        self.awaiting_identity = None;
        self.code_section = None;
        // A rule/begin line still pending at a boundary (e.g. EOF right after
        // it) must not fall out of the partition.
        self.flush_pending_into_current();
        match std::mem::replace(&mut self.state, State::Idle { raw_since: None }) {
            State::InCompilation { comp } => self.close_compilation(comp, end),
            State::Idle {
                raw_since: Some(start),
            } if start < end => {
                self.raw.push(RawSection {
                    lines: start..end,
                    label: self.raw_label.take().unwrap_or_default(),
                });
            }
            State::Idle { .. } => {}
        }
    }
}

fn label_from(line: &[u8]) -> String {
    let mut label = ansi::to_display_string(line);
    if label.len() > 96 {
        let cut = (0..=96)
            .rev()
            .find(|&i| label.is_char_boundary(i))
            .unwrap_or(0);
        label.truncate(cut);
        label.push('…');
    }
    label
}

/// Parses one `[…]` lifecycle line into an event, or `None` if it is not one
/// (programs can print bracketed lines of their own; never guess).
fn parse_event(text: &str) -> Option<EventKind> {
    let r = res();

    if text.starts_with("[marking ") {
        let c = r.ev_marking.captures(text)?;
        return Some(EventKind::Marking {
            name: c[1].to_string(),
            sfi: Addr::parse(&c[2]),
            target: Tier::parse(&c[3]),
            reason: c[4].to_string(),
        });
    }
    if text.starts_with("[compiling method ") {
        let c = r.ev_compile_start.captures(text)?;
        return Some(EventKind::CompileStart {
            name: c[1].to_string(),
            sfi: Addr::parse(&c[2]),
            target: Tier::parse(&c[3]),
            osr: c.get(4).is_some(),
        });
    }
    if text.starts_with("[completed compiling ") {
        let c = r.ev_compile_done.captures(text)?;
        return Some(EventKind::CompileDone {
            name: c[1].to_string(),
            sfi: Addr::parse(&c[2]),
            target: Tier::parse(&c[3]),
            osr: c.get(4).is_some(),
        });
    }
    if text.starts_with("[bailout (") {
        let c = r.ev_deopt_begin.captures(text)?;
        return Some(EventKind::DeoptBegin {
            kind: c[1].to_string(),
            reason: c[2].to_string(),
            name: c[3].to_string(),
            sfi: Addr::parse(&c[4]),
            tier: Tier::parse(&c[5]),
            opt_id: c[6].parse().ok(),
            bytecode_offset: c[7].parse().ok(),
        });
    }
    if text.starts_with("[bailout end") {
        let c = r.ev_deopt_end.captures(text)?;
        return Some(EventKind::DeoptEnd {
            invalidated: &c[1] == "invalidated",
        });
    }
    if text.starts_with("[OSR - ") {
        let c = r.ev_osr.captures(text)?;
        return Some(EventKind::Osr {
            what: c[1].to_string(),
            name: c[2].to_string(),
            osr_offset: c.get(3).and_then(|m| m.as_str().parse().ok()),
        });
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    fn index(text: &str) -> TraceIndex {
        let mut buffer = LogBuffer::new();
        buffer.append(text.as_bytes());
        buffer.finish();
        let mut idx = TraceIndex::new(None);
        idx.ingest(&buffer, true);
        idx
    }

    /// Sections must partition the line range: no gaps, no overlaps.
    fn assert_partition(idx: &TraceIndex, line_count: usize) {
        let mut ranges: Vec<(usize, usize)> = idx
            .compilations
            .iter()
            .map(|c| (c.lines.start, c.lines.end))
            .chain(idx.raw.iter().map(|r| (r.lines.start, r.lines.end)))
            .collect();
        ranges.sort();
        let mut at = 0;
        for (start, end) in ranges {
            assert_eq!(start, at, "gap or overlap at line {at}");
            assert!(end >= start);
            at = end;
        }
        assert_eq!(at, line_count, "sections do not cover the file");
    }

    const V152: &str = "\
V8 is running with developer-only features enabled.
---------------------------------------------------
Begin compiling method add using Maglev
Compiling 0x09b80101e371 <JSFunction add (sfi = 0x9b80101e2cd)> with Maglev
----- Bytecode array -----
Parameter count 3
----- Maglev graph building -----
Graph
   9: CheckedSmiUntag [n2], 1 uses
----- Register allocation -----
    9/9: CheckedSmiUntag [v5/n2:[x0|R|t]] \u{2192} [x0|R|w32]
---------------------------------------------------
Finished compiling method add using Maglev
";

    #[test]
    fn v152_shape_indexes_one_compilation() {
        let idx = index(V152);
        assert_eq!(idx.compilations.len(), 1);
        let c = &idx.compilations[0];
        assert_eq!(c.name, "add");
        assert_eq!(c.key.tier, Tier::Maglev);
        assert_eq!(c.key.ordinal, 1);
        // Starts at the rule line, ends after the Finished line.
        assert_eq!(c.lines, 1..13);
        assert_eq!(c.phases.len(), 3);
        assert_eq!(c.phases[0].kind, PhaseKind::Bytecode);
        assert_eq!(c.phases[1].kind, PhaseKind::Graph { known: true });
        // The trailing rule + Finished lines live in the last phase's range.
        assert_eq!(c.phases[2].lines, 9..13);
        assert_partition(&idx, 13);
        assert_eq!(idx.detected_version.as_deref(), Some("15.2"));
    }

    #[test]
    fn v149_shape_without_begin_finished() {
        let idx = index(
            "\
Compiling 0x1 <JSFunction a (sfi = 0x10)> with Maglev
----- After graph building -----
   1: Foo
Compiling 0x2 <JSFunction b (sfi = 0x20)> with Maglev
----- After graph building -----
   1: Bar
",
        );
        assert_eq!(idx.compilations.len(), 2);
        assert_eq!(idx.compilations[0].lines, 0..3);
        assert_eq!(idx.compilations[1].lines, 3..6);
        assert_partition(&idx, 6);
        assert_eq!(idx.detected_version.as_deref(), Some("14.9"));
    }

    #[test]
    fn toplevel_empty_name_parses() {
        let idx = index("Compiling 0x1 <JSFunction (sfi = 0x10)> with Maglev\n");
        assert_eq!(idx.compilations.len(), 1);
        assert_eq!(idx.compilations[0].name, "");
        assert_eq!(idx.compilations[0].display_name(), "<toplevel>");
    }

    #[test]
    fn same_key_gets_ordinals() {
        let idx = index(
            "\
Compiling 0x1 <JSFunction f (sfi = 0x10)> with Maglev
Compiling 0x1 <JSFunction f (sfi = 0x10)> with Maglev
",
        );
        assert_eq!(idx.compilations[0].key.ordinal, 1);
        assert_eq!(idx.compilations[1].key.ordinal, 2);
    }

    #[test]
    fn events_are_parsed_and_close_compilations() {
        let idx = index(
            "\
[marking 0x09b8 <JSFunction f (sfi = 0x10)> for optimization to MAGLEV, ConcurrencyMode::kConcurrent, reason: hot and stable]
Compiling 0x1 <JSFunction f (sfi = 0x10)> with Maglev
----- Maglev graph building -----
   1: Foo
[bailout (kind: deopt-eager, reason: not a Smi): begin. deoptimizing 0x09b8 <JSFunction f (sfi = 0x10)>, 0x031a <Code MAGLEV>, opt id 1, bytecode offset 2, deopt exit 0, FP to SP delta 32, caller SP 0x0001, pc 0x0002]
trailing program output
",
        );
        assert_eq!(idx.events.len(), 2);
        assert!(matches!(
            idx.events[0].kind,
            EventKind::Marking { ref name, .. } if name == "f"
        ));
        let EventKind::DeoptBegin {
            ref reason,
            bytecode_offset,
            ..
        } = idx.events[1].kind
        else {
            panic!("expected deopt event");
        };
        assert_eq!(reason, "not a Smi");
        assert_eq!(bytecode_offset, Some(2));
        // The bailout closed the compilation; the event line + trailing output
        // are raw.
        assert_eq!(idx.compilations[0].lines, 1..4);
        assert_partition(&idx, 6);
    }

    #[test]
    fn osr_flag_binds_by_sfi_and_tier() {
        let idx = index(
            "\
[OSR - compilation started. function: hot, osr offset: 28, mode: ConcurrencyMode::kSynchronous]
[compiling method 0x1 <JSFunction hot (sfi = 0x10)> (target MAGLEV) OSR, mode: ConcurrencyMode::kSynchronous]
Compiling 0x1 <JSFunction hot (sfi = 0x10)> with Maglev
----- Maglev graph building -----
",
        );
        let osr = idx.compilations[0].osr.as_ref().expect("osr flagged");
        assert_eq!(osr.offset, Some(28));
        assert_eq!(osr.confidence, Confidence::Heuristic);
    }

    #[test]
    fn non_event_bracket_lines_are_content() {
        let idx = index("[object Object]\n[1, 2, 3]\n");
        assert!(idx.events.is_empty());
        assert_eq!(idx.raw.len(), 1);
        assert_eq!(idx.raw[0].label, "[object Object]");
    }

    #[test]
    fn function_filter_marks_but_keeps_sections() {
        let mut buffer = LogBuffer::new();
        buffer.append(
            b"Compiling 0x1 <JSFunction keepme (sfi = 0x10)> with Maglev
Compiling 0x2 <JSFunction dropme (sfi = 0x20)> with Maglev
",
        );
        buffer.finish();
        let mut idx = TraceIndex::new(Some(Regex::new("^keep").unwrap()));
        idx.ingest(&buffer, true);
        assert!(!idx.compilations[0].filtered_out);
        assert!(idx.compilations[1].filtered_out);
        assert_partition(&idx, 2);
    }

    #[test]
    fn streaming_holds_back_the_partial_line() {
        let mut buffer = LogBuffer::new();
        let mut idx = TraceIndex::new(None);
        buffer.append(b"Compiling 0x1 <JSFunction f (sfi = 0x10)> with Mag");
        idx.ingest(&buffer, false);
        assert_eq!(idx.compilations.len(), 0);
        buffer.append(b"lev\n----- Maglev graph building -----\n");
        idx.ingest(&buffer, false);
        assert_eq!(idx.compilations.len(), 1);
        buffer.finish();
        idx.ingest(&buffer, true);
        assert_eq!(idx.compilations[0].phases.len(), 1);
    }

    #[test]
    fn ansi_wrapped_boundaries_still_match() {
        let idx =
            index("\u{1b}[0;32mCompiling 0x1 <JSFunction f (sfi = 0x10)> with Maglev\u{1b}[0m\n");
        assert_eq!(idx.compilations.len(), 1);
    }

    /// Turbolev-frontend dumps have no `Compiling` line: the anchor is the
    /// `Bytecode before MaglevGraphBuilding` banner, and identity arrives on
    /// the `Function:` line inside the section.
    #[test]
    fn turbolev_anchor_and_identity() {
        let idx = index(
            "\
warmup
----- Bytecode before MaglevGraphBuilding -----

Function: 0x9 <JSFunction add (sfi = 0x77)>
Parameter count 3
----- Maglev graph building -----
   1: Foo
----- Bytecode before MaglevGraphBuilding -----

Function: 0x9 <JSFunction add (sfi = 0x77)>
----- Maglev graph building -----
   2: Bar
",
        );
        assert_eq!(idx.compilations.len(), 2);
        let a = &idx.compilations[0];
        assert_eq!(a.key.tier, Tier::Turbolev);
        assert_eq!(a.key.sfi, Addr(0x77));
        assert_eq!(a.key.ordinal, 1);
        assert_eq!(a.name, "add");
        assert_eq!(a.lines, 1..7);
        assert_eq!(a.phases.len(), 2);
        assert_eq!(a.phases[0].kind, PhaseKind::Bytecode);
        assert_eq!(a.phases[1].kind, PhaseKind::Graph { known: true });
        assert_eq!(idx.compilations[1].key.ordinal, 2);
        assert_partition(&idx, 12);
        assert_eq!(idx.detected_version.as_deref(), Some("15.2"));
    }

    /// Newer builds print `Begin compiling method X using TurboFan` ahead of
    /// a *Turbolev* pipeline dump — the tier word is misleading, and only
    /// the `Bytecode before MaglevGraphBuilding` banner reveals the
    /// pipeline. This must yield ONE Turbolev section, not a three-line
    /// Turbofan stub plus a separate Turbolev one (user report).
    #[test]
    fn begin_turbofan_then_turbolev_banner_is_one_section() {
        let idx = index(
            "\
---------------------------------------------------
Begin compiling method add using TurboFan
----- Bytecode before MaglevGraphBuilding -----
Function: 0x9 <JSFunction add (sfi = 0x77)>
----- Maglev graph building -----
   1: Foo
---------------------------------------------------
Finished compiling method add using TurboFan
",
        );
        assert_eq!(idx.compilations.len(), 1, "one section, not a TF stub");
        let c = &idx.compilations[0];
        assert_eq!(c.key.tier, Tier::Turbolev);
        assert_eq!(c.key.sfi, Addr(0x77));
        assert_eq!(c.key.ordinal, 1);
        assert_eq!(c.name, "add");
        assert_eq!(
            c.lines,
            0..8,
            "rule + Begin head the section; the TurboFan trailer closes it"
        );
        assert_eq!(c.phases.len(), 2);
        assert_eq!(c.phases[0].kind, PhaseKind::Bytecode);
        assert_eq!(c.phases[1].kind, PhaseKind::Graph { known: true });
        assert_partition(&idx, 8);
    }

    /// With concurrent recompilation, A's trailer can land inside B's body.
    /// It must not close B: the end marker names its own method, and a
    /// mismatched name means "interleaved content of whoever is open" —
    /// closing there glued A's trailer onto B and orphaned B's own trailer
    /// as a raw section (user report).
    #[test]
    fn mismatched_finished_trailer_does_not_close_the_open_section() {
        let idx = index(
            "\
Begin compiling method A using TurboFan
----- Bytecode before MaglevGraphBuilding -----
   1: Foo
Begin compiling method B using TurboFan
----- Bytecode before MaglevGraphBuilding -----
   1: Foo
Finished compiling method A using TurboFan
Finished compiling method B using TurboFan
",
        );
        assert_eq!(idx.compilations.len(), 2);
        assert_eq!(idx.compilations[0].name, "A");
        assert_eq!(idx.compilations[0].lines, 0..3);
        assert_eq!(
            idx.compilations[1].lines,
            3..8,
            "A's stray trailer stays interleaved content; B closes at B's trailer"
        );
        assert!(idx.raw.is_empty(), "no orphaned trailer: {:?}", idx.raw);
        assert_partition(&idx, 8);
    }

    /// A `Function:` line with no awaiting Turbolev compilation is ordinary
    /// content, and a compilation whose identity never arrives stays visible
    /// with the placeholder key.
    #[test]
    fn turbolev_identity_edge_cases() {
        let idx = index("Function: 0x9 <JSFunction f (sfi = 0x77)>\n");
        assert!(idx.compilations.is_empty());
        assert_eq!(idx.raw.len(), 1);

        let idx = index(
            "\
----- Bytecode before MaglevGraphBuilding -----
Parameter count 3
",
        );
        assert_eq!(idx.compilations.len(), 1);
        assert_eq!(idx.compilations[0].key.sfi, Addr(0));
        assert_eq!(idx.compilations[0].display_name(), "<toplevel>");
        assert_partition(&idx, 2);
    }

    /// An event arriving while rule/`Begin` lines are pending must not orphan
    /// them from the partition (found in review: the cut used to end the
    /// compilation before the pending lines while raw opened at the event).
    #[test]
    fn event_after_pending_lines_keeps_the_partition() {
        let idx = index(
            "\
Compiling 0x1 <JSFunction f (sfi = 0x10)> with Maglev
----- Maglev graph building -----
   1: Foo
---------------------------------------------------
Begin compiling method g using Maglev
[bailout (kind: deopt-eager, reason: x): begin. deoptimizing 0x2 <JSFunction g (sfi = 0x20)>, 0x3 <Code MAGLEV>, opt id 1, bytecode offset 2, deopt exit 0, FP to SP delta 32, caller SP 0x4, pc 0x5]
",
        );
        assert_eq!(idx.compilations[0].lines, 0..3);
        // The rule + Begin lines land in the raw section with the event.
        assert_eq!(idx.raw[0].lines, 3..6);
        assert_partition(&idx, 6);
    }

    #[test]
    fn garbage_never_panics_and_partitions() {
        let noise = "-----\n---- x ----\nCompiling gibberish\n[bailout mangled\n\u{fffd}\u{1b}[9\n";
        let idx = index(noise);
        assert_partition(&idx, 5);
    }

    /// `--trace-turbo-graph` (Phase 8.1): the Begin line is the anchor, and
    /// the SFI is patched from the first SFI object matching the Begin name.
    #[test]
    fn turbofan_begin_anchors_and_identity_patches() {
        let idx = index(
            "\
warmup
---------------------------------------------------
Begin compiling method add using TurboFan
----- Graph after V8.TFBytecodeGraphBuilder -----
#0:Start()
#16:FrameState[UNOPTIMIZED_FRAME, 2, Ignore, 0x9b80101e305 <SharedFunctionInfo add>](#0:Start)
----- schedule -----
--- BLOCK B0 id0 ---
  20: End(19)
---------------------------------------------------
Finished compiling method add using TurboFan
",
        );
        assert_eq!(idx.compilations.len(), 1);
        let c = &idx.compilations[0];
        assert_eq!(c.key.tier, Tier::Turbofan);
        assert_eq!(c.key.sfi, Addr(0x9b80101e305));
        assert_eq!(c.key.ordinal, 1);
        assert_eq!(c.name, "add");
        assert_eq!(c.lines, 1..11, "the rule lines belong to the section");
        assert_eq!(c.phases.len(), 2);
        assert_eq!(c.phases[0].kind, PhaseKind::Graph { known: true });
        assert_eq!(c.phases[1].name, "schedule");
        assert_partition(&idx, 11);
    }

    /// Identity binds only through a FrameState's SFI object with the
    /// matching name — a `HeapConstant[<JSFunction …>]` can be a closure of
    /// a *different* function that shares the name, and node print order
    /// guarantees nothing (found in review). A section with no such line
    /// stays honestly unidentified, with a 1-based provisional ordinal.
    #[test]
    fn turbofan_identity_requires_a_matching_framestate() {
        let idx = index(
            "\
Begin compiling method add using TurboFan
----- Graph after V8.TFInlining -----
#5:HeapConstant[0x1 <JSFunction add (sfi = 0xdead)>]()
#7:FrameState[UNOPTIMIZED_FRAME, 2, Ignore, 0x99 <SharedFunctionInfo other>](#0:Start)
#16:FrameState[UNOPTIMIZED_FRAME, 2, Ignore, 0xbeef <SharedFunctionInfo add>](#0:Start)
",
        );
        assert_eq!(
            idx.compilations[0].key.sfi,
            Addr(0xbeef),
            "the closure constant (0xdead) and the inlined frame (0x99) must not win"
        );

        let idx = index(
            "\
Begin compiling method add using TurboFan
----- Graph after V8.TFInlining -----
#6:HeapConstant[0x2 <JSFunction add (sfi = 0x42)>]()
",
        );
        assert_eq!(
            idx.compilations[0].key.sfi,
            Addr(0),
            "no FrameState, no guess"
        );
        assert_eq!(idx.compilations[0].key.ordinal, 1, "provisional, 1-based");
    }

    /// `--print-opt-code` (Phase 8.2): Raw source anchors, the key/value
    /// header supplies identity, End code closes.
    #[test]
    fn opt_code_sections_index_with_identity() {
        let idx = index(
            "\
--- Raw source ---
(a, b) {
  return a + b;
}
--- Optimized code ---
optimization_id = 1
kind = TURBOFAN_JS
name = add
Instructions (size = 288)
0x1700001a0     0  a9bf7bfd       stp fp, lr, [sp, #-16]!
Safepoints (stack slots = 6, byte size = 17)
RelocInfo (size = 13)
--- End code ---
trailing
",
        );
        assert_eq!(idx.compilations.len(), 1);
        let c = &idx.compilations[0];
        assert_eq!(c.name, "add");
        assert_eq!(c.key.tier, Tier::Turbofan);
        assert_eq!(c.key.ordinal, 1);
        assert_eq!(c.lines, 0..13, "End code included");
        let names: Vec<&str> = c.phases.iter().map(|p| p.name.as_str()).collect();
        assert_eq!(
            names,
            ["Optimized code", "Instructions", "Safepoints", "RelocInfo"]
        );
        assert!(c.phases.iter().all(|p| p.kind == PhaseKind::Listing));
        assert_eq!(c.preamble, 1..4, "the raw source is the preamble");
        assert_partition(&idx, 14);
    }

    /// Review m6/partition: an event inside a TurboFan section degrades the
    /// tail to raw, and a Maglev `Finished` trailer must not close a
    /// TurboFan section.
    #[test]
    fn turbofan_sections_survive_interleaving() {
        let idx = index(
            "\
Begin compiling method add using TurboFan
----- Graph after V8.TFTyper -----
#0:Start()
[bailout (kind: deopt-eager, reason: x): begin. deoptimizing 0x2 <JSFunction g (sfi = 0x20)>, 0x3 <Code MAGLEV>, opt id 1, bytecode offset 2, deopt exit 0, FP to SP delta 32, caller SP 0x4, pc 0x5]
tail
",
        );
        assert_eq!(idx.compilations[0].lines, 0..3);
        assert_eq!(idx.raw[0].lines, 3..5);
        assert_partition(&idx, 5);

        let idx = index(
            "\
Begin compiling method add using TurboFan
----- Graph after V8.TFTyper -----
#0:Start()
Finished compiling method other using Maglev
#1:End(#0:Start)
",
        );
        assert_eq!(
            idx.compilations[0].lines,
            0..5,
            "a Maglev trailer does not close a TurboFan section"
        );
        assert_partition(&idx, 5);
    }

    /// Review M4: the Raw-source block is optional — `--- Optimized code ---`
    /// itself anchors when no code section is open.
    #[test]
    fn opt_code_without_raw_source_still_anchors() {
        let idx = index(
            "\
--- Optimized code ---
kind = TURBOFAN_JS
name = add
Instructions (size = 288)
0x1700001a0     0  a9bf7bfd       stp fp, lr, [sp, #-16]!
--- End code ---
",
        );
        assert_eq!(idx.compilations.len(), 1);
        let c = &idx.compilations[0];
        assert_eq!(c.name, "add");
        assert_eq!(c.key.ordinal, 1);
        let names: Vec<&str> = c.phases.iter().map(|p| p.name.as_str()).collect();
        assert_eq!(names, ["Optimized code", "Instructions"]);
        assert_partition(&idx, 6);
    }

    /// `--print-bytecode` (Phase 8.3): full identity on the anchor line,
    /// pool/table headers open listing phases — but only for Ignition;
    /// inside a Turbolev bytecode dump the same lines stay content.
    #[test]
    fn bytecode_anchor_and_tables() {
        let idx = index(
            "\
[generated bytecode for function: add (0x9b80101e2cd <SharedFunctionInfo add>)]
Parameter count 3
         0x31a010000c0 @    0 : 0b 04             Ldar a1
Constant pool (size = 0)
Handler Table (size = 0)
Source Position Table (size = 0)
[generated bytecode for function:  (0x9b80101e265 <SharedFunctionInfo>)]
Parameter count 1
",
        );
        assert_eq!(idx.compilations.len(), 2);
        let c = &idx.compilations[0];
        assert_eq!(c.key.tier, Tier::Ignition);
        assert_eq!(c.key.sfi, Addr(0x9b80101e2cd));
        assert_eq!(c.name, "add");
        let names: Vec<&str> = c.phases.iter().map(|p| p.name.as_str()).collect();
        assert_eq!(
            names,
            [
                "Bytecode array",
                "Constant pool",
                "Handler Table",
                "Source Position Table"
            ]
        );
        assert_eq!(idx.compilations[1].display_name(), "<toplevel>");
        assert_partition(&idx, 8);

        // Turbolev's bytecode section prints the same table headers; they
        // must not fragment its phases.
        let idx = index(
            "\
----- Bytecode before MaglevGraphBuilding -----
Function: 0x9 <JSFunction add (sfi = 0x77)>
Constant pool (size = 0)
Handler Table (size = 0)
----- Maglev graph building -----
   1: Foo
",
        );
        assert_eq!(idx.compilations.len(), 1);
        assert_eq!(idx.compilations[0].phases.len(), 2, "no listing phases");
    }
}
